### ISSUE TITLE
Progress Bar and HTTP ERROR on Bigger Files

### ISSUE THREAD

**Issue by baberzaman** [Convertio/convertio-php#13]
Hi,
This API Solved my very big problem. But, I am having 2 issues. 
1. I want to show the PROGRESS bar while it is converting file. Progress bar where users can see there file is being converted. 0 to 100%

2. When i try to convert a Bigger file. 25 or 30 MB, it gives HTTP ERROR. 

I am having only these 2 issues. Kindly Reply me soon with these please.

```
require_once 'convertio-php-master/autoload.php';
 use \Convertio\Convertio;
  use \Convertio\Exceptions\APIException;
  use \Convertio\Exceptions\CURLException;

		$image_name = $_FILES['audio']['name'];
		$image_size =$_FILES['audio']['size'];
		$image_tmp =$_FILES['audio']['tmp_name'];
		$image_name = $image_name;
		$runn = move_uploaded_file($image_tmp,'temp_music/'.$image_name);
		
		if($runn){
		$fil = explode('.', $image_name);
		$FileName = $fil[0];
		$RenameValue = $FileName.'_MU.mp3';
		$_SESSION['FileName'] = $RenameValue;
	
      $API = new Convertio("API KEY REMOVED");        
     $API->startFromURL('https://musicuploads.com.au/musicuploads/temp_music/'.$image_name, 'mp3')   // Convert (Render) HTML Page to PNG
	 
  ->wait()  // Wait for conversion finish
  
  ->download('./converted_files/'.$RenameValue)                // Download Result To Local File
  ->delete();  
	$delTemp = unlink('temp_music/'.$image_name);
  
if($delTemp){
echo '<script>location.href="music_converted.php"</script>';
}
 }
 ```

Kindly Provide me Response Soon

**Comment by Dantist** [comment]
Hello!

1. Instead of `wait()` call you should periodically query status of the file like this:
```
do {
    usleep(500000);
    $API->status();
    $progress = $API->step_percent;
} while ($API->step === 'convert');
```
and this will do the trick with the progress. 

2. We were able to find your account. The issue in your particular conversions was reated to a malformed URLs. You should call API like this: `$API->startFromURL(urlencode($url), 'mp3)->..`

P.S. From the security point of view you should sanitize all variables you get from user, especially, `$image_name` one in your particular example.
